// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kur;

#nullable disable

namespace kur.Migrations
{
    [DbContext(typeof(Entities))]
    [Migration("20250525165830_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kur.Phonemes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Phoneme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phonemes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Phoneme = "А"
                        },
                        new
                        {
                            Id = 2,
                            Phoneme = "Б"
                        },
                        new
                        {
                            Id = 3,
                            Phoneme = "В"
                        },
                        new
                        {
                            Id = 4,
                            Phoneme = "Г"
                        },
                        new
                        {
                            Id = 5,
                            Phoneme = "Д"
                        },
                        new
                        {
                            Id = 6,
                            Phoneme = "Е"
                        },
                        new
                        {
                            Id = 7,
                            Phoneme = "Ё"
                        },
                        new
                        {
                            Id = 8,
                            Phoneme = "Ж"
                        },
                        new
                        {
                            Id = 9,
                            Phoneme = "З"
                        },
                        new
                        {
                            Id = 10,
                            Phoneme = "И"
                        },
                        new
                        {
                            Id = 11,
                            Phoneme = "Й"
                        },
                        new
                        {
                            Id = 12,
                            Phoneme = "К"
                        },
                        new
                        {
                            Id = 13,
                            Phoneme = "Л"
                        },
                        new
                        {
                            Id = 14,
                            Phoneme = "М"
                        },
                        new
                        {
                            Id = 15,
                            Phoneme = "Н"
                        },
                        new
                        {
                            Id = 16,
                            Phoneme = "О"
                        },
                        new
                        {
                            Id = 17,
                            Phoneme = "П"
                        },
                        new
                        {
                            Id = 18,
                            Phoneme = "Р"
                        },
                        new
                        {
                            Id = 19,
                            Phoneme = "С"
                        },
                        new
                        {
                            Id = 20,
                            Phoneme = "Т"
                        },
                        new
                        {
                            Id = 21,
                            Phoneme = "У"
                        },
                        new
                        {
                            Id = 22,
                            Phoneme = "Ф"
                        },
                        new
                        {
                            Id = 23,
                            Phoneme = "Х"
                        },
                        new
                        {
                            Id = 24,
                            Phoneme = "Ц"
                        },
                        new
                        {
                            Id = 25,
                            Phoneme = "Ч"
                        },
                        new
                        {
                            Id = 26,
                            Phoneme = "Ш"
                        },
                        new
                        {
                            Id = 27,
                            Phoneme = "Щ"
                        },
                        new
                        {
                            Id = 28,
                            Phoneme = "Ъ"
                        },
                        new
                        {
                            Id = 29,
                            Phoneme = "Ы"
                        },
                        new
                        {
                            Id = 30,
                            Phoneme = "Ь"
                        },
                        new
                        {
                            Id = 31,
                            Phoneme = "Э"
                        },
                        new
                        {
                            Id = 32,
                            Phoneme = "Ю"
                        },
                        new
                        {
                            Id = 33,
                            Phoneme = "Я"
                        });
                });

            modelBuilder.Entity("kur.RhymeTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RhymeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RhymeTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RhymeName = "Точная"
                        },
                        new
                        {
                            Id = 2,
                            RhymeName = "Неточная"
                        },
                        new
                        {
                            Id = 3,
                            RhymeName = "Ассонанс"
                        },
                        new
                        {
                            Id = 4,
                            RhymeName = "Диссонанс"
                        },
                        new
                        {
                            Id = 5,
                            RhymeName = "Мужская"
                        },
                        new
                        {
                            Id = 6,
                            RhymeName = "Женская"
                        },
                        new
                        {
                            Id = 7,
                            RhymeName = "Дактилическая"
                        },
                        new
                        {
                            Id = 8,
                            RhymeName = "Гипердактилическая"
                        },
                        new
                        {
                            Id = 9,
                            RhymeName = "Богатая"
                        },
                        new
                        {
                            Id = 10,
                            RhymeName = "Бедная"
                        },
                        new
                        {
                            Id = 11,
                            RhymeName = "Составная"
                        },
                        new
                        {
                            Id = 12,
                            RhymeName = "Кольцевая"
                        },
                        new
                        {
                            Id = 13,
                            RhymeName = "Перекрестная"
                        },
                        new
                        {
                            Id = 14,
                            RhymeName = "Парная"
                        },
                        new
                        {
                            Id = 15,
                            RhymeName = "Охватная"
                        },
                        new
                        {
                            Id = 16,
                            RhymeName = "Свободная"
                        },
                        new
                        {
                            Id = 17,
                            RhymeName = "Внутренняя"
                        },
                        new
                        {
                            Id = 18,
                            RhymeName = "Начальная"
                        },
                        new
                        {
                            Id = 19,
                            RhymeName = "Конечная"
                        },
                        new
                        {
                            Id = 20,
                            RhymeName = "Полная"
                        });
                });

            modelBuilder.Entity("kur.Rhymes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RhymeId")
                        .HasColumnType("int");

                    b.Property<int>("RhymeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RhymeId");

                    b.HasIndex("RhymeTypeId");

                    b.HasIndex("WordId");

                    b.ToTable("Rhymes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RhymeId = 2,
                            RhymeTypeId = 1,
                            WordId = 1
                        },
                        new
                        {
                            Id = 2,
                            RhymeId = 4,
                            RhymeTypeId = 1,
                            WordId = 3
                        },
                        new
                        {
                            Id = 3,
                            RhymeId = 6,
                            RhymeTypeId = 2,
                            WordId = 5
                        },
                        new
                        {
                            Id = 4,
                            RhymeId = 8,
                            RhymeTypeId = 1,
                            WordId = 7
                        },
                        new
                        {
                            Id = 5,
                            RhymeId = 10,
                            RhymeTypeId = 1,
                            WordId = 9
                        },
                        new
                        {
                            Id = 6,
                            RhymeId = 12,
                            RhymeTypeId = 1,
                            WordId = 11
                        },
                        new
                        {
                            Id = 7,
                            RhymeId = 14,
                            RhymeTypeId = 1,
                            WordId = 13
                        },
                        new
                        {
                            Id = 8,
                            RhymeId = 16,
                            RhymeTypeId = 1,
                            WordId = 15
                        },
                        new
                        {
                            Id = 9,
                            RhymeId = 18,
                            RhymeTypeId = 1,
                            WordId = 17
                        },
                        new
                        {
                            Id = 10,
                            RhymeId = 20,
                            RhymeTypeId = 2,
                            WordId = 19
                        },
                        new
                        {
                            Id = 11,
                            RhymeId = 22,
                            RhymeTypeId = 3,
                            WordId = 21
                        },
                        new
                        {
                            Id = 12,
                            RhymeId = 24,
                            RhymeTypeId = 1,
                            WordId = 23
                        },
                        new
                        {
                            Id = 13,
                            RhymeId = 26,
                            RhymeTypeId = 2,
                            WordId = 25
                        },
                        new
                        {
                            Id = 14,
                            RhymeId = 28,
                            RhymeTypeId = 2,
                            WordId = 27
                        },
                        new
                        {
                            Id = 15,
                            RhymeId = 30,
                            RhymeTypeId = 3,
                            WordId = 29
                        },
                        new
                        {
                            Id = 16,
                            RhymeId = 32,
                            RhymeTypeId = 2,
                            WordId = 31
                        },
                        new
                        {
                            Id = 17,
                            RhymeId = 34,
                            RhymeTypeId = 1,
                            WordId = 33
                        },
                        new
                        {
                            Id = 18,
                            RhymeId = 36,
                            RhymeTypeId = 2,
                            WordId = 35
                        },
                        new
                        {
                            Id = 19,
                            RhymeId = 36,
                            RhymeTypeId = 1,
                            WordId = 37
                        },
                        new
                        {
                            Id = 20,
                            RhymeId = 39,
                            RhymeTypeId = 2,
                            WordId = 38
                        },
                        new
                        {
                            Id = 21,
                            RhymeId = 41,
                            RhymeTypeId = 3,
                            WordId = 40
                        },
                        new
                        {
                            Id = 22,
                            RhymeId = 43,
                            RhymeTypeId = 1,
                            WordId = 42
                        },
                        new
                        {
                            Id = 23,
                            RhymeId = 45,
                            RhymeTypeId = 1,
                            WordId = 44
                        },
                        new
                        {
                            Id = 24,
                            RhymeId = 47,
                            RhymeTypeId = 1,
                            WordId = 46
                        },
                        new
                        {
                            Id = 25,
                            RhymeId = 49,
                            RhymeTypeId = 1,
                            WordId = 48
                        },
                        new
                        {
                            Id = 26,
                            RhymeId = 51,
                            RhymeTypeId = 2,
                            WordId = 50
                        },
                        new
                        {
                            Id = 27,
                            RhymeId = 53,
                            RhymeTypeId = 1,
                            WordId = 52
                        },
                        new
                        {
                            Id = 28,
                            RhymeId = 55,
                            RhymeTypeId = 1,
                            WordId = 54
                        },
                        new
                        {
                            Id = 29,
                            RhymeId = 57,
                            RhymeTypeId = 1,
                            WordId = 56
                        },
                        new
                        {
                            Id = 30,
                            RhymeId = 59,
                            RhymeTypeId = 1,
                            WordId = 58
                        },
                        new
                        {
                            Id = 31,
                            RhymeId = 61,
                            RhymeTypeId = 1,
                            WordId = 60
                        },
                        new
                        {
                            Id = 32,
                            RhymeId = 63,
                            RhymeTypeId = 1,
                            WordId = 62
                        },
                        new
                        {
                            Id = 33,
                            RhymeId = 65,
                            RhymeTypeId = 1,
                            WordId = 64
                        },
                        new
                        {
                            Id = 34,
                            RhymeId = 33,
                            RhymeTypeId = 2,
                            WordId = 66
                        },
                        new
                        {
                            Id = 35,
                            RhymeId = 68,
                            RhymeTypeId = 1,
                            WordId = 67
                        },
                        new
                        {
                            Id = 36,
                            RhymeId = 70,
                            RhymeTypeId = 1,
                            WordId = 69
                        },
                        new
                        {
                            Id = 37,
                            RhymeId = 72,
                            RhymeTypeId = 1,
                            WordId = 71
                        },
                        new
                        {
                            Id = 38,
                            RhymeId = 74,
                            RhymeTypeId = 1,
                            WordId = 73
                        },
                        new
                        {
                            Id = 39,
                            RhymeId = 15,
                            RhymeTypeId = 1,
                            WordId = 75
                        },
                        new
                        {
                            Id = 40,
                            RhymeId = 77,
                            RhymeTypeId = 1,
                            WordId = 76
                        },
                        new
                        {
                            Id = 41,
                            RhymeId = 79,
                            RhymeTypeId = 1,
                            WordId = 78
                        },
                        new
                        {
                            Id = 42,
                            RhymeId = 81,
                            RhymeTypeId = 1,
                            WordId = 80
                        },
                        new
                        {
                            Id = 43,
                            RhymeId = 83,
                            RhymeTypeId = 1,
                            WordId = 82
                        },
                        new
                        {
                            Id = 44,
                            RhymeId = 85,
                            RhymeTypeId = 2,
                            WordId = 84
                        },
                        new
                        {
                            Id = 45,
                            RhymeId = 87,
                            RhymeTypeId = 1,
                            WordId = 86
                        },
                        new
                        {
                            Id = 46,
                            RhymeId = 89,
                            RhymeTypeId = 1,
                            WordId = 88
                        },
                        new
                        {
                            Id = 47,
                            RhymeId = 91,
                            RhymeTypeId = 1,
                            WordId = 90
                        },
                        new
                        {
                            Id = 48,
                            RhymeId = 93,
                            RhymeTypeId = 1,
                            WordId = 92
                        },
                        new
                        {
                            Id = 49,
                            RhymeId = 95,
                            RhymeTypeId = 2,
                            WordId = 94
                        },
                        new
                        {
                            Id = 50,
                            RhymeId = 77,
                            RhymeTypeId = 2,
                            WordId = 96
                        },
                        new
                        {
                            Id = 51,
                            RhymeId = 98,
                            RhymeTypeId = 1,
                            WordId = 97
                        },
                        new
                        {
                            Id = 52,
                            RhymeId = 100,
                            RhymeTypeId = 2,
                            WordId = 99
                        },
                        new
                        {
                            Id = 53,
                            RhymeId = 102,
                            RhymeTypeId = 1,
                            WordId = 101
                        },
                        new
                        {
                            Id = 54,
                            RhymeId = 104,
                            RhymeTypeId = 2,
                            WordId = 103
                        },
                        new
                        {
                            Id = 55,
                            RhymeId = 106,
                            RhymeTypeId = 1,
                            WordId = 105
                        },
                        new
                        {
                            Id = 56,
                            RhymeId = 108,
                            RhymeTypeId = 1,
                            WordId = 107
                        },
                        new
                        {
                            Id = 57,
                            RhymeId = 110,
                            RhymeTypeId = 1,
                            WordId = 109
                        },
                        new
                        {
                            Id = 58,
                            RhymeId = 112,
                            RhymeTypeId = 1,
                            WordId = 111
                        },
                        new
                        {
                            Id = 59,
                            RhymeId = 114,
                            RhymeTypeId = 1,
                            WordId = 113
                        },
                        new
                        {
                            Id = 60,
                            RhymeId = 116,
                            RhymeTypeId = 2,
                            WordId = 115
                        },
                        new
                        {
                            Id = 61,
                            RhymeId = 118,
                            RhymeTypeId = 1,
                            WordId = 117
                        },
                        new
                        {
                            Id = 62,
                            RhymeId = 120,
                            RhymeTypeId = 1,
                            WordId = 119
                        },
                        new
                        {
                            Id = 63,
                            RhymeId = 122,
                            RhymeTypeId = 1,
                            WordId = 121
                        },
                        new
                        {
                            Id = 64,
                            RhymeId = 124,
                            RhymeTypeId = 2,
                            WordId = 123
                        },
                        new
                        {
                            Id = 65,
                            RhymeId = 126,
                            RhymeTypeId = 1,
                            WordId = 125
                        },
                        new
                        {
                            Id = 66,
                            RhymeId = 128,
                            RhymeTypeId = 1,
                            WordId = 127
                        },
                        new
                        {
                            Id = 67,
                            RhymeId = 130,
                            RhymeTypeId = 2,
                            WordId = 129
                        },
                        new
                        {
                            Id = 68,
                            RhymeId = 132,
                            RhymeTypeId = 2,
                            WordId = 131
                        },
                        new
                        {
                            Id = 69,
                            RhymeId = 134,
                            RhymeTypeId = 2,
                            WordId = 133
                        },
                        new
                        {
                            Id = 70,
                            RhymeId = 136,
                            RhymeTypeId = 2,
                            WordId = 135
                        },
                        new
                        {
                            Id = 71,
                            RhymeId = 138,
                            RhymeTypeId = 2,
                            WordId = 137
                        },
                        new
                        {
                            Id = 72,
                            RhymeId = 140,
                            RhymeTypeId = 2,
                            WordId = 139
                        },
                        new
                        {
                            Id = 73,
                            RhymeId = 142,
                            RhymeTypeId = 2,
                            WordId = 141
                        },
                        new
                        {
                            Id = 74,
                            RhymeId = 144,
                            RhymeTypeId = 1,
                            WordId = 143
                        },
                        new
                        {
                            Id = 75,
                            RhymeId = 146,
                            RhymeTypeId = 2,
                            WordId = 145
                        },
                        new
                        {
                            Id = 76,
                            RhymeId = 148,
                            RhymeTypeId = 2,
                            WordId = 147
                        },
                        new
                        {
                            Id = 77,
                            RhymeId = 150,
                            RhymeTypeId = 2,
                            WordId = 149
                        },
                        new
                        {
                            Id = 78,
                            RhymeId = 152,
                            RhymeTypeId = 2,
                            WordId = 151
                        },
                        new
                        {
                            Id = 79,
                            RhymeId = 154,
                            RhymeTypeId = 1,
                            WordId = 153
                        },
                        new
                        {
                            Id = 80,
                            RhymeId = 156,
                            RhymeTypeId = 1,
                            WordId = 155
                        },
                        new
                        {
                            Id = 81,
                            RhymeId = 158,
                            RhymeTypeId = 2,
                            WordId = 157
                        },
                        new
                        {
                            Id = 82,
                            RhymeId = 160,
                            RhymeTypeId = 2,
                            WordId = 159
                        },
                        new
                        {
                            Id = 83,
                            RhymeId = 162,
                            RhymeTypeId = 2,
                            WordId = 161
                        });
                });

            modelBuilder.Entity("kur.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "admin",
                            Role = 1
                        });
                });

            modelBuilder.Entity("kur.WordPhonemes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhonemeId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhonemeId");

                    b.HasIndex("WordId");

                    b.ToTable("WordPhonemes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhonemeId = 14,
                            Position = 1,
                            WordId = 1
                        },
                        new
                        {
                            Id = 2,
                            PhonemeId = 10,
                            Position = 2,
                            WordId = 1
                        },
                        new
                        {
                            Id = 3,
                            PhonemeId = 18,
                            Position = 3,
                            WordId = 1
                        },
                        new
                        {
                            Id = 4,
                            PhonemeId = 19,
                            Position = 1,
                            WordId = 2
                        },
                        new
                        {
                            Id = 5,
                            PhonemeId = 7,
                            Position = 2,
                            WordId = 2
                        },
                        new
                        {
                            Id = 6,
                            PhonemeId = 31,
                            Position = 3,
                            WordId = 2
                        },
                        new
                        {
                            Id = 7,
                            PhonemeId = 20,
                            Position = 4,
                            WordId = 2
                        },
                        new
                        {
                            Id = 8,
                            PhonemeId = 13,
                            Position = 1,
                            WordId = 3
                        },
                        new
                        {
                            Id = 9,
                            PhonemeId = 21,
                            Position = 2,
                            WordId = 3
                        },
                        new
                        {
                            Id = 10,
                            PhonemeId = 2,
                            Position = 3,
                            WordId = 3
                        },
                        new
                        {
                            Id = 11,
                            PhonemeId = 15,
                            Position = 4,
                            WordId = 3
                        },
                        new
                        {
                            Id = 12,
                            PhonemeId = 3,
                            Position = 5,
                            WordId = 3
                        },
                        new
                        {
                            Id = 13,
                            PhonemeId = 2,
                            Position = 6,
                            WordId = 3
                        },
                        new
                        {
                            Id = 14,
                            PhonemeId = 9,
                            Position = 1,
                            WordId = 4
                        },
                        new
                        {
                            Id = 15,
                            PhonemeId = 16,
                            Position = 2,
                            WordId = 4
                        },
                        new
                        {
                            Id = 16,
                            PhonemeId = 3,
                            Position = 3,
                            WordId = 4
                        },
                        new
                        {
                            Id = 17,
                            PhonemeId = 30,
                            Position = 4,
                            WordId = 4
                        },
                        new
                        {
                            Id = 18,
                            PhonemeId = 2,
                            Position = 1,
                            WordId = 5
                        },
                        new
                        {
                            Id = 19,
                            PhonemeId = 18,
                            Position = 2,
                            WordId = 5
                        },
                        new
                        {
                            Id = 20,
                            PhonemeId = 3,
                            Position = 3,
                            WordId = 5
                        },
                        new
                        {
                            Id = 21,
                            PhonemeId = 14,
                            Position = 4,
                            WordId = 5
                        },
                        new
                        {
                            Id = 22,
                            PhonemeId = 10,
                            Position = 5,
                            WordId = 5
                        });
                });

            modelBuilder.Entity("kur.Words", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("StressPosition")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StressPosition = 2,
                            Word = "любовь"
                        },
                        new
                        {
                            Id = 2,
                            StressPosition = 1,
                            Word = "кровь"
                        },
                        new
                        {
                            Id = 3,
                            StressPosition = 1,
                            Word = "снова"
                        },
                        new
                        {
                            Id = 4,
                            StressPosition = 2,
                            Word = "слова"
                        },
                        new
                        {
                            Id = 5,
                            StressPosition = 2,
                            Word = "мечта"
                        },
                        new
                        {
                            Id = 6,
                            StressPosition = 1,
                            Word = "света"
                        },
                        new
                        {
                            Id = 7,
                            StressPosition = 2,
                            Word = "звезда"
                        },
                        new
                        {
                            Id = 8,
                            StressPosition = 2,
                            Word = "вода"
                        },
                        new
                        {
                            Id = 9,
                            StressPosition = 2,
                            Word = "огонь"
                        },
                        new
                        {
                            Id = 10,
                            StressPosition = 1,
                            Word = "конь"
                        },
                        new
                        {
                            Id = 11,
                            StressPosition = 1,
                            Word = "день"
                        },
                        new
                        {
                            Id = 12,
                            StressPosition = 1,
                            Word = "тень"
                        },
                        new
                        {
                            Id = 13,
                            StressPosition = 1,
                            Word = "путь"
                        },
                        new
                        {
                            Id = 14,
                            StressPosition = 1,
                            Word = "грудь"
                        },
                        new
                        {
                            Id = 15,
                            StressPosition = 1,
                            Word = "друг"
                        },
                        new
                        {
                            Id = 16,
                            StressPosition = 1,
                            Word = "круг"
                        },
                        new
                        {
                            Id = 17,
                            StressPosition = 2,
                            Word = "рука"
                        },
                        new
                        {
                            Id = 18,
                            StressPosition = 2,
                            Word = "река"
                        },
                        new
                        {
                            Id = 19,
                            StressPosition = 2,
                            Word = "душа"
                        },
                        new
                        {
                            Id = 20,
                            StressPosition = 3,
                            Word = "тишина"
                        },
                        new
                        {
                            Id = 21,
                            StressPosition = 2,
                            Word = "весна"
                        },
                        new
                        {
                            Id = 22,
                            StressPosition = 2,
                            Word = "зима"
                        },
                        new
                        {
                            Id = 23,
                            StressPosition = 2,
                            Word = "луна"
                        },
                        new
                        {
                            Id = 24,
                            StressPosition = 2,
                            Word = "волна"
                        },
                        new
                        {
                            Id = 25,
                            StressPosition = 2,
                            Word = "судьба"
                        },
                        new
                        {
                            Id = 26,
                            StressPosition = 2,
                            Word = "тоска"
                        },
                        new
                        {
                            Id = 27,
                            StressPosition = 1,
                            Word = "песня"
                        },
                        new
                        {
                            Id = 28,
                            StressPosition = 1,
                            Word = "травка"
                        },
                        new
                        {
                            Id = 29,
                            StressPosition = 1,
                            Word = "сердце"
                        },
                        new
                        {
                            Id = 30,
                            StressPosition = 1,
                            Word = "солнце"
                        },
                        new
                        {
                            Id = 31,
                            StressPosition = 1,
                            Word = "небо"
                        },
                        new
                        {
                            Id = 32,
                            StressPosition = 1,
                            Word = "ветер"
                        },
                        new
                        {
                            Id = 33,
                            StressPosition = 1,
                            Word = "пламя"
                        },
                        new
                        {
                            Id = 34,
                            StressPosition = 1,
                            Word = "знамя"
                        },
                        new
                        {
                            Id = 35,
                            StressPosition = 1,
                            Word = "поле"
                        },
                        new
                        {
                            Id = 36,
                            StressPosition = 1,
                            Word = "море"
                        },
                        new
                        {
                            Id = 37,
                            StressPosition = 1,
                            Word = "горе"
                        },
                        new
                        {
                            Id = 38,
                            StressPosition = 1,
                            Word = "радость"
                        },
                        new
                        {
                            Id = 39,
                            StressPosition = 1,
                            Word = "счастье"
                        },
                        new
                        {
                            Id = 40,
                            StressPosition = 1,
                            Word = "жизнь"
                        },
                        new
                        {
                            Id = 41,
                            StressPosition = 1,
                            Word = "смерть"
                        },
                        new
                        {
                            Id = 42,
                            StressPosition = 1,
                            Word = "свет"
                        },
                        new
                        {
                            Id = 43,
                            StressPosition = 1,
                            Word = "цвет"
                        },
                        new
                        {
                            Id = 44,
                            StressPosition = 1,
                            Word = "дом"
                        },
                        new
                        {
                            Id = 45,
                            StressPosition = 1,
                            Word = "сом"
                        },
                        new
                        {
                            Id = 46,
                            StressPosition = 1,
                            Word = "лес"
                        },
                        new
                        {
                            Id = 47,
                            StressPosition = 1,
                            Word = "вес"
                        },
                        new
                        {
                            Id = 48,
                            StressPosition = 1,
                            Word = "сон"
                        },
                        new
                        {
                            Id = 49,
                            StressPosition = 1,
                            Word = "тон"
                        },
                        new
                        {
                            Id = 50,
                            StressPosition = 1,
                            Word = "мир"
                        },
                        new
                        {
                            Id = 51,
                            StressPosition = 1,
                            Word = "птица"
                        },
                        new
                        {
                            Id = 52,
                            StressPosition = 1,
                            Word = "улица"
                        },
                        new
                        {
                            Id = 53,
                            StressPosition = 1,
                            Word = "дверь"
                        },
                        new
                        {
                            Id = 54,
                            StressPosition = 1,
                            Word = "тень"
                        },
                        new
                        {
                            Id = 55,
                            StressPosition = 1,
                            Word = "воля"
                        },
                        new
                        {
                            Id = 56,
                            StressPosition = 1,
                            Word = "доля"
                        },
                        new
                        {
                            Id = 57,
                            StressPosition = 2,
                            Word = "земля"
                        },
                        new
                        {
                            Id = 58,
                            StressPosition = 2,
                            Word = "семья"
                        },
                        new
                        {
                            Id = 59,
                            StressPosition = 1,
                            Word = "книга"
                        },
                        new
                        {
                            Id = 60,
                            StressPosition = 1,
                            Word = "лига"
                        },
                        new
                        {
                            Id = 61,
                            StressPosition = 1,
                            Word = "вера"
                        },
                        new
                        {
                            Id = 62,
                            StressPosition = 1,
                            Word = "мера"
                        },
                        new
                        {
                            Id = 63,
                            StressPosition = 1,
                            Word = "слава"
                        },
                        new
                        {
                            Id = 64,
                            StressPosition = 1,
                            Word = "пава"
                        },
                        new
                        {
                            Id = 65,
                            StressPosition = 2,
                            Word = "тропа"
                        },
                        new
                        {
                            Id = 66,
                            StressPosition = 2,
                            Word = "европа"
                        },
                        new
                        {
                            Id = 67,
                            StressPosition = 1,
                            Word = "дерево"
                        },
                        new
                        {
                            Id = 68,
                            StressPosition = 1,
                            Word = "пламя"
                        },
                        new
                        {
                            Id = 69,
                            StressPosition = 1,
                            Word = "камни"
                        },
                        new
                        {
                            Id = 70,
                            StressPosition = 1,
                            Word = "дни"
                        },
                        new
                        {
                            Id = 71,
                            StressPosition = 1,
                            Word = "звери"
                        },
                        new
                        {
                            Id = 72,
                            StressPosition = 1,
                            Word = "двери"
                        },
                        new
                        {
                            Id = 73,
                            StressPosition = 2,
                            Word = "песок"
                        },
                        new
                        {
                            Id = 74,
                            StressPosition = 2,
                            Word = "носок"
                        },
                        new
                        {
                            Id = 75,
                            StressPosition = 1,
                            Word = "берег"
                        },
                        new
                        {
                            Id = 76,
                            StressPosition = 2,
                            Word = "ковчег"
                        },
                        new
                        {
                            Id = 77,
                            StressPosition = 1,
                            Word = "луг"
                        },
                        new
                        {
                            Id = 78,
                            StressPosition = 1,
                            Word = "друг"
                        },
                        new
                        {
                            Id = 79,
                            StressPosition = 1,
                            Word = "снег"
                        },
                        new
                        {
                            Id = 80,
                            StressPosition = 1,
                            Word = "век"
                        },
                        new
                        {
                            Id = 81,
                            StressPosition = 2,
                            Word = "цветок"
                        },
                        new
                        {
                            Id = 82,
                            StressPosition = 2,
                            Word = "поток"
                        },
                        new
                        {
                            Id = 83,
                            StressPosition = 1,
                            Word = "голос"
                        },
                        new
                        {
                            Id = 84,
                            StressPosition = 1,
                            Word = "колос"
                        },
                        new
                        {
                            Id = 85,
                            StressPosition = 1,
                            Word = "взгляд"
                        },
                        new
                        {
                            Id = 86,
                            StressPosition = 1,
                            Word = "сад"
                        },
                        new
                        {
                            Id = 87,
                            StressPosition = 1,
                            Word = "меч"
                        },
                        new
                        {
                            Id = 88,
                            StressPosition = 1,
                            Word = "печь"
                        },
                        new
                        {
                            Id = 89,
                            StressPosition = 1,
                            Word = "песнь"
                        },
                        new
                        {
                            Id = 90,
                            StressPosition = 1,
                            Word = "честность"
                        },
                        new
                        {
                            Id = 91,
                            StressPosition = 2,
                            Word = "дорога"
                        },
                        new
                        {
                            Id = 92,
                            StressPosition = 2,
                            Word = "нога"
                        },
                        new
                        {
                            Id = 93,
                            StressPosition = 2,
                            Word = "береза"
                        },
                        new
                        {
                            Id = 94,
                            StressPosition = 2,
                            Word = "слеза"
                        },
                        new
                        {
                            Id = 95,
                            StressPosition = 1,
                            Word = "сила"
                        },
                        new
                        {
                            Id = 96,
                            StressPosition = 2,
                            Word = "мила"
                        },
                        new
                        {
                            Id = 97,
                            StressPosition = 2,
                            Word = "свобода"
                        },
                        new
                        {
                            Id = 98,
                            StressPosition = 2,
                            Word = "природа"
                        },
                        new
                        {
                            Id = 99,
                            StressPosition = 2,
                            Word = "победа"
                        },
                        new
                        {
                            Id = 100,
                            StressPosition = 2,
                            Word = "беда"
                        },
                        new
                        {
                            Id = 101,
                            StressPosition = 3,
                            Word = "человек"
                        },
                        new
                        {
                            Id = 102,
                            StressPosition = 1,
                            Word = "век"
                        },
                        new
                        {
                            Id = 103,
                            StressPosition = 2,
                            Word = "любить"
                        },
                        new
                        {
                            Id = 104,
                            StressPosition = 2,
                            Word = "простить"
                        },
                        new
                        {
                            Id = 105,
                            StressPosition = 2,
                            Word = "лететь"
                        },
                        new
                        {
                            Id = 106,
                            StressPosition = 2,
                            Word = "смотреть"
                        },
                        new
                        {
                            Id = 107,
                            StressPosition = 2,
                            Word = "идти"
                        },
                        new
                        {
                            Id = 108,
                            StressPosition = 2,
                            Word = "нести"
                        },
                        new
                        {
                            Id = 109,
                            StressPosition = 1,
                            Word = "петь"
                        },
                        new
                        {
                            Id = 110,
                            StressPosition = 2,
                            Word = "светить"
                        },
                        new
                        {
                            Id = 111,
                            StressPosition = 1,
                            Word = "ждать"
                        },
                        new
                        {
                            Id = 112,
                            StressPosition = 2,
                            Word = "искать"
                        },
                        new
                        {
                            Id = 113,
                            StressPosition = 2,
                            Word = "мечтать"
                        },
                        new
                        {
                            Id = 114,
                            StressPosition = 2,
                            Word = "страдать"
                        },
                        new
                        {
                            Id = 115,
                            StressPosition = 2,
                            Word = "гореть"
                        },
                        new
                        {
                            Id = 116,
                            StressPosition = 2,
                            Word = "творец"
                        },
                        new
                        {
                            Id = 117,
                            StressPosition = 2,
                            Word = "бежать"
                        },
                        new
                        {
                            Id = 118,
                            StressPosition = 2,
                            Word = "лежать"
                        },
                        new
                        {
                            Id = 119,
                            StressPosition = 2,
                            Word = "кричать"
                        },
                        new
                        {
                            Id = 120,
                            StressPosition = 2,
                            Word = "молчать"
                        },
                        new
                        {
                            Id = 121,
                            StressPosition = 2,
                            Word = "дышать"
                        },
                        new
                        {
                            Id = 122,
                            StressPosition = 2,
                            Word = "писать"
                        },
                        new
                        {
                            Id = 123,
                            StressPosition = 2,
                            Word = "читать"
                        },
                        new
                        {
                            Id = 124,
                            StressPosition = 1,
                            Word = "звать"
                        },
                        new
                        {
                            Id = 125,
                            StressPosition = 1,
                            Word = "дать"
                        },
                        new
                        {
                            Id = 126,
                            StressPosition = 1,
                            Word = "взять"
                        },
                        new
                        {
                            Id = 127,
                            StressPosition = 1,
                            Word = "знать"
                        },
                        new
                        {
                            Id = 128,
                            StressPosition = 1,
                            Word = "спать"
                        },
                        new
                        {
                            Id = 129,
                            StressPosition = 2,
                            Word = "стоять"
                        },
                        new
                        {
                            Id = 130,
                            StressPosition = 2,
                            Word = "гулять"
                        },
                        new
                        {
                            Id = 131,
                            StressPosition = 2,
                            Word = "смеять"
                        },
                        new
                        {
                            Id = 132,
                            StressPosition = 1,
                            Word = "плакать"
                        },
                        new
                        {
                            Id = 133,
                            StressPosition = 2,
                            Word = "бросать"
                        },
                        new
                        {
                            Id = 134,
                            StressPosition = 1,
                            Word = "росать"
                        },
                        new
                        {
                            Id = 135,
                            StressPosition = 1,
                            Word = "видеть"
                        },
                        new
                        {
                            Id = 136,
                            StressPosition = 2,
                            Word = "сидеть"
                        },
                        new
                        {
                            Id = 137,
                            StressPosition = 2,
                            Word = "держать"
                        },
                        new
                        {
                            Id = 138,
                            StressPosition = 2,
                            Word = "рожать"
                        },
                        new
                        {
                            Id = 139,
                            StressPosition = 1,
                            Word = "думать"
                        },
                        new
                        {
                            Id = 140,
                            StressPosition = 2,
                            Word = "просить"
                        },
                        new
                        {
                            Id = 141,
                            StressPosition = 2,
                            Word = "хитрить"
                        },
                        new
                        {
                            Id = 142,
                            StressPosition = 2,
                            Word = "творить"
                        },
                        new
                        {
                            Id = 143,
                            StressPosition = 2,
                            Word = "бродить"
                        },
                        new
                        {
                            Id = 144,
                            StressPosition = 2,
                            Word = "водить"
                        },
                        new
                        {
                            Id = 145,
                            StressPosition = 2,
                            Word = "сверкать"
                        },
                        new
                        {
                            Id = 146,
                            StressPosition = 1,
                            Word = "меркать"
                        },
                        new
                        {
                            Id = 147,
                            StressPosition = 2,
                            Word = "шагать"
                        },
                        new
                        {
                            Id = 148,
                            StressPosition = 1,
                            Word = "бегать"
                        },
                        new
                        {
                            Id = 149,
                            StressPosition = 1,
                            Word = "плавать"
                        },
                        new
                        {
                            Id = 150,
                            StressPosition = 1,
                            Word = "править"
                        },
                        new
                        {
                            Id = 151,
                            StressPosition = 1,
                            Word = "славить"
                        },
                        new
                        {
                            Id = 152,
                            StressPosition = 2,
                            Word = "ловить"
                        },
                        new
                        {
                            Id = 153,
                            StressPosition = 2,
                            Word = "свободный"
                        },
                        new
                        {
                            Id = 154,
                            StressPosition = 2,
                            Word = "родной"
                        },
                        new
                        {
                            Id = 155,
                            StressPosition = 2,
                            Word = "высокий"
                        },
                        new
                        {
                            Id = 156,
                            StressPosition = 2,
                            Word = "глубокий"
                        },
                        new
                        {
                            Id = 157,
                            StressPosition = 1,
                            Word = "ясный"
                        },
                        new
                        {
                            Id = 158,
                            StressPosition = 1,
                            Word = "красный"
                        },
                        new
                        {
                            Id = 159,
                            StressPosition = 1,
                            Word = "чистый"
                        },
                        new
                        {
                            Id = 160,
                            StressPosition = 2,
                            Word = "простой"
                        },
                        new
                        {
                            Id = 161,
                            StressPosition = 1,
                            Word = "светлый"
                        },
                        new
                        {
                            Id = 162,
                            StressPosition = 1,
                            Word = "летний"
                        },
                        new
                        {
                            Id = 163,
                            StressPosition = 1,
                            Word = "зимний"
                        },
                        new
                        {
                            Id = 164,
                            StressPosition = 2,
                            Word = "весенний"
                        },
                        new
                        {
                            Id = 165,
                            StressPosition = 2,
                            Word = "осенний"
                        },
                        new
                        {
                            Id = 166,
                            StressPosition = 2,
                            Word = "далекий"
                        },
                        new
                        {
                            Id = 167,
                            StressPosition = 1,
                            Word = "близкий"
                        },
                        new
                        {
                            Id = 168,
                            StressPosition = 2,
                            Word = "горячий"
                        },
                        new
                        {
                            Id = 169,
                            StressPosition = 1,
                            Word = "холодный"
                        },
                        new
                        {
                            Id = 170,
                            StressPosition = 1,
                            Word = "мудрый"
                        },
                        new
                        {
                            Id = 171,
                            StressPosition = 1,
                            Word = "добрый"
                        },
                        new
                        {
                            Id = 172,
                            StressPosition = 1,
                            Word = "смелый"
                        },
                        new
                        {
                            Id = 173,
                            StressPosition = 1,
                            Word = "верный"
                        },
                        new
                        {
                            Id = 174,
                            StressPosition = 1,
                            Word = "честный"
                        },
                        new
                        {
                            Id = 175,
                            StressPosition = 1,
                            Word = "грустный"
                        },
                        new
                        {
                            Id = 176,
                            StressPosition = 2,
                            Word = "веселый"
                        },
                        new
                        {
                            Id = 177,
                            StressPosition = 2,
                            Word = "пустой"
                        },
                        new
                        {
                            Id = 178,
                            StressPosition = 1,
                            Word = "крепкий"
                        },
                        new
                        {
                            Id = 179,
                            StressPosition = 1,
                            Word = "цепкий"
                        },
                        new
                        {
                            Id = 180,
                            StressPosition = 1,
                            Word = "быстрый"
                        },
                        new
                        {
                            Id = 181,
                            StressPosition = 1,
                            Word = "острый"
                        },
                        new
                        {
                            Id = 182,
                            StressPosition = 1,
                            Word = "мягкий"
                        },
                        new
                        {
                            Id = 183,
                            StressPosition = 1,
                            Word = "гладкий"
                        },
                        new
                        {
                            Id = 184,
                            StressPosition = 1,
                            Word = "шаткий"
                        },
                        new
                        {
                            Id = 185,
                            StressPosition = 1,
                            Word = "рваный"
                        },
                        new
                        {
                            Id = 186,
                            StressPosition = 2,
                            Word = "прямой"
                        },
                        new
                        {
                            Id = 187,
                            StressPosition = 2,
                            Word = "кривой"
                        },
                        new
                        {
                            Id = 188,
                            StressPosition = 2,
                            Word = "живой"
                        },
                        new
                        {
                            Id = 189,
                            StressPosition = 1,
                            Word = "свежий"
                        },
                        new
                        {
                            Id = 190,
                            StressPosition = 1,
                            Word = "нежный"
                        },
                        new
                        {
                            Id = 191,
                            StressPosition = 1,
                            Word = "белый"
                        },
                        new
                        {
                            Id = 192,
                            StressPosition = 1,
                            Word = "синий"
                        },
                        new
                        {
                            Id = 193,
                            StressPosition = 3,
                            Word = "зеленый"
                        },
                        new
                        {
                            Id = 194,
                            StressPosition = 1,
                            Word = "серый"
                        },
                        new
                        {
                            Id = 195,
                            StressPosition = 1,
                            Word = "черный"
                        },
                        new
                        {
                            Id = 196,
                            StressPosition = 1,
                            Word = "яркий"
                        },
                        new
                        {
                            Id = 197,
                            StressPosition = 1,
                            Word = "темный"
                        },
                        new
                        {
                            Id = 198,
                            StressPosition = 1,
                            Word = "бледный"
                        },
                        new
                        {
                            Id = 199,
                            StressPosition = 2,
                            Word = "громкий"
                        },
                        new
                        {
                            Id = 200,
                            StressPosition = 1,
                            Word = "тонкий"
                        });
                });

            modelBuilder.Entity("kur.Rhymes", b =>
                {
                    b.HasOne("kur.Words", "Rhyme")
                        .WithMany()
                        .HasForeignKey("RhymeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kur.RhymeTypes", "RhymeType")
                        .WithMany()
                        .HasForeignKey("RhymeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kur.Words", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rhyme");

                    b.Navigation("RhymeType");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("kur.WordPhonemes", b =>
                {
                    b.HasOne("kur.Phonemes", "Phoneme")
                        .WithMany()
                        .HasForeignKey("PhonemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kur.Words", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phoneme");

                    b.Navigation("Word");
                });
#pragma warning restore 612, 618
        }
    }
}
